import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#09090b" },
    { media: "(prefers-color-scheme: dark)", color: "#09090b" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-zinc-950">
      <body className="min-h-screen bg-zinc-950 text-zinc-50">
      <header
        className="
          sticky top-0 z-50
          border-b border-zinc-800
          bg-zinc-950/95 backdrop-blur
          pt-[env(safe-area-inset-top)]
        "
      >
          <div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-4">
            <a href="/" className="font-semibold tracking-tight text-zinc-50">
              Carter Tate
            </a>
            <nav className="flex gap-4 text-sm text-zinc-300">
              <a className="hover:text-zinc-50" href="/#about">About Me</a>
              <a className="hover:text-zinc-50" href="/#projects">Projects</a>
              <a className="hover:text-zinc-50" href="/#internship">Internship Experience</a>
              <a className="hover:text-zinc-50" href="/#contact">Contact</a>
              <a className="hover:text-zinc-50" href="/resume">Resume</a>
            </nav>
          </div>
        </header>

        <main>{children}</main>

        <footer className="border-t border-zinc-800">
          <div className="mx-auto max-w-4xl px-6 py-6 text-sm text-zinc-400">
            © {new Date().getFullYear()} Carter Tate
          </div>
        </footer>
      </body>

    </html>
  );
}
